### ISSUE TITLE
Error when updating from 0.8.29 to 0.8.30

### ISSUE THREAD

**Issue by schimmy** [boboldehampsink/import#110]
Hello,

I've been having issues upgrading from 0.2.29 to 0.2.30. I see on EVERY page (not just the admin page):
```
2016/04/11 23:50:41 [trace] [system.db.CDbCommand] Querying SQL: SELECT `locale`
FROM `craft_locales`
ORDER BY `sortOrder`
in /var/www/craft/app/services/LocalizationService.php (126)
in /var/www/craft/app/services/LocalizationService.php (173)
in /var/www/craft/app/etc/behaviors/AppBehavior.php (737)
2016/04/11 23:50:41 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT `locale`
FROM `craft_locales`
ORDER BY `sortOrder`)
2016/04/11 23:50:41 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT `locale`
FROM `craft_locales`
ORDER BY `sortOrder`)
2016/04/11 23:50:42 [error] [exception.Craft\HttpException.503] exception 'Craft\HttpException' in /var/www/craft/app/etc/web/WebApp.php:934
Stack trace:
#0 /var/www/craft/app/etc/web/WebApp.php(260): Craft\WebApp->_processUpdateLogic()
#1 /var/www/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#2 /var/www/craft/app/index.php(62): CApplication->run()
#3 /var/www/html/index.php(19): require_once('/var/www/craft/...')
#4 {main}
REQUEST_URI=/
```

So every request to the website causes a 503. I've isolated it down to the commit where I update the Import plugin.

This is after the update seems to go successfully:
```
2016/04/11 23:50:37 [profile] [system.db.CDbCommand.execute] end:system.db.CDbCommand.execute(UPDATE `craft_plugins` SET `version`=:version, `schemaVersion`=:schemaVersion, `dateUpdated`=:dateUpdated WHERE `class`=:pRI0EBPRhy. Bound with :pRI0EBPRhy='Import', :version='0.8.30', :schemaVersion=NULL, :dateUpdated='2016-04-11 23:50:37')
2016/04/11 23:50:37 [info] [application] [Forced] Taking the site out of maintenance mode.
...
2016/04/11 23:50:37 [info] [application] [Forced] The plugin "Import" is done updating the database.
```

I've tried uninstalling and reinstalling the plugin, but haven't touched the database manually yet.

This is a problem, as I really like this plugin!
Please let me know how I can fix this, I'm ok losing all history.

**Comment by schimmy** [comment]
for some reason, today I can't replicate - closing
