### ISSUE TITLE
Error when importing entries that have a parent entry

### ISSUE THREAD

**Issue by jayelkaake** [boboldehampsink/import#59]
It seems like the parent entry field is unhandled. 
Exporting entries with multi-level content where the slug is the same as another entry fails. Here's the error I get in my craft.log:
```
015/06/17 18:15:29 [error] [php] Undefined index: entrytype (/bc-craft/craft/plugins/import/services/Import_EntryService.php:66)
Stack trace:
#0 /bc-craft/craft/app/services/TasksService.php(238): Craft\ImportTask->runStep()
#1 /bc-craft/craft/app/services/TasksService.php(199): Craft\TasksService->runTask()
#2 /bc-craft/craft/app/controllers/TasksController.php(119): Craft\TasksService->runPendingTasks()
#3 /bc-craft/craft/app/framework/web/actions/CInlineAction.php(49): Craft\TasksController->actionRerunTask()
#4 /bc-craft/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /bc-craft/craft/app/framework/web/CController.php(286): Craft\TasksController->runAction()
#6 /bc-craft/craft/app/framework/web/CController.php(265): Craft\TasksController->runActionWithFilters()
#7 /bc-craft/craft/app/framework/web/CWebApplication.php(282): Craft\TasksController->run()
#8 /bc-craft/craft/app/etc/web/WebApp.php(784): Craft\WebApp->runController()
#9 /bc-craft/craft/app/etc/web/WebApp.php(276): Craft\WebApp->_processActionRequest()
#10 /bc-craft/craft/app/framework/base/CApplication.php(184): Craft\WebApp->processRequest()
#11 /bc-craft/craft/app/index.php(62): Craft\WebApp->run()
#12 /bc-craft/public/index.php(39): require_once()
```

**Comment by boboldehampsink** [comment]
It looks like you're not using the latest version

**Comment by jayelkaake** [comment]
Thanks for the quick response!
Actually we are using the latest version: 
![](http://monosnap.com/image/NzxvUxgxrIppTlzK7VHEk6pEQ1EQYy.png)

Actually the issue is 2 separate things:
1. You can't import multi-level entry data.
2. An error occurs when you have multi-level data that contains the same slugs for different pages. For example:
```
1. Features (url is /features and slug is 'features'
2. Enterprise (url is /enterprise and slug is 'enterprise'
    2.1 Features (url is /enterprise/features, slug is 'features')

Any idea?
Aside from this, your plugin is extremely well built, nice work.

**Comment by boboldehampsink** [comment]
You should be able to use multi-level entry data! I'll look into the other issue.
